# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.1
_src_path: gh:oca/oca-addons-repo-template
dependency_installation_mode: PIP
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: null
repo_name: mis-builder
repo_slug: mis-builder
travis_apt_packages: []
travis_apt_sources: []
